// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlD-dWCa9Y9hauKTxHEV3zADfyct9jG1g',
    appId: '1:945294278060:web:5713c1dcc6e1b5bf884e09',
    messagingSenderId: '945294278060',
    projectId: 'campusconnect-49054',
    authDomain: 'campusconnect-49054.firebaseapp.com',
    storageBucket: 'campusconnect-49054.firebasestorage.app',
    measurementId: 'G-E273Z6MWM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_PgqD0sNVuJXyx541gfzes0vx4E9g9o',
    appId: '1:945294278060:android:8c44703a94fb090d884e09',
    messagingSenderId: '945294278060',
    projectId: 'campusconnect-49054',
    storageBucket: 'campusconnect-49054.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWpNumPJe2GQHvLFW9dLLawMpv2R-5WQ',
    appId: '1:945294278060:ios:52c465c0713135ad884e09',
    messagingSenderId: '945294278060',
    projectId: 'campusconnect-49054',
    storageBucket: 'campusconnect-49054.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWpNumPJe2GQHvLFW9dLLawMpv2R-5WQ',
    appId: '1:945294278060:ios:52c465c0713135ad884e09',
    messagingSenderId: '945294278060',
    projectId: 'campusconnect-49054',
    storageBucket: 'campusconnect-49054.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlD-dWCa9Y9hauKTxHEV3zADfyct9jG1g',
    appId: '1:945294278060:web:458efdde1a4fa656884e09',
    messagingSenderId: '945294278060',
    projectId: 'campusconnect-49054',
    authDomain: 'campusconnect-49054.firebaseapp.com',
    storageBucket: 'campusconnect-49054.firebasestorage.app',
    measurementId: 'G-VLC5HT011Y',
  );
}
