// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0uFxl0hIDZ8_-tlIpIoFS4_qyau21ZA',
    appId: '1:1085604551549:web:0b6387590499ea18bb0a14',
    messagingSenderId: '1085604551549',
    projectId: 'campus-connect-7a533',
    authDomain: 'campus-connect-7a533.firebaseapp.com',
    storageBucket: 'campus-connect-7a533.firebasestorage.app',
    measurementId: 'G-9T7E4SVQ3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELE2UxMuGdHZ6aOpiZbyJRhEIMKkis38',
    appId: '1:1085604551549:android:e7d1365d8990db2bbb0a14',
    messagingSenderId: '1085604551549',
    projectId: 'campus-connect-7a533',
    storageBucket: 'campus-connect-7a533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSrBRmHKUKRCrqrHnIZ6htb3lp5CPdQM',
    appId: '1:1085604551549:ios:3b5347e50628ff7fbb0a14',
    messagingSenderId: '1085604551549',
    projectId: 'campus-connect-7a533',
    storageBucket: 'campus-connect-7a533.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );
}
